### ISSUE TITLE
Suggestions for Plugin Extension Manager

### ISSUE THREAD

**Issue by yuen619** [Gandi-IDE/gandi-plugins#65]
I found that the extension in the plugin extension manager ExtensionBox can be checked, so why not support batch selection and deletion? @fath11 
![image](https://github.com/Gandi-IDE/gandi-plugins/assets/100176335/26789d59-8f43-45c5-8404-bb3c506e447f)
Then if the ExtensionBox is displayed and the extension is installed later, we need to reopen the ExtensionBox to see it. Can you optimize it?

**Comment by fath11** [comment]
batch selection and deletion are already a thing. when you check multiple extensions, the delete button for those selected extensions will only appear on one of them and if you click it, it will delete all selected extensions.

as for the second issue, i forgot that it was there so i didnt fix it in my latest PR ;-;

**Comment by yuen619** [comment]
Addendum: If the editor language and extension i10n are not supported, an error will be reported if the extension information cannot be read, resulting in 
![image](https://github.com/Gandi-IDE/gandi-plugins/assets/100176335/7f6e42cf-07b5-454f-8330-cdfe6e281f0d)
vendor~main.4658b0e2.js:2 
 
TypeError: Cannot read properties of undefined (reading 'spriteEffect.extensionName')
    at vendor~main.4658b0e2.js:245:816412
    at Array.reduce (<anonymous>)
    at Object.getAllExtensionInfo (vendor~main.4658b0e2.js:245:816290)
    at plugin-extension-man…er.50602.js:1:18107
    at plugin-extension-man…er.50602.js:1:18188
    at Array.map (<anonymous>)
    at b (plugin-extension-man…er.50602.js:1:17561)
    at plugin-extension-man…er.50602.js:1:18338
    at rs (main.js?t=1719566542876:2:139529)
    at _u (main.js?t=1719566542876:2:159474)
    at main.js?t=1719566542876:2:158251
    at ku (main.js?t=1719566542876:2:158311)
    at uu (main.js?t=1719566542876:2:152127)
    at jr (main.js?t=1719566542876:2:93103)
    at main.js?t=1719566542876:2:149555. How about adding a try catch ...? I know he's Gandi's problem, but it's better to deal with it. @fath11

**Comment by yuen619** [comment]
Please handle the situation where the selected language extension in the editor does not correspond to i10n, and if the extension information cannot be obtained, an error message will appear. Add a try catch... may solve the problem
